### ISSUE TITLE
Dashes and hyphens 

### ISSUE THREAD

**Issue by aliaksandrkazlou** [aliaksandrkazlou/texts_comparison#5]
As per [here](https://github.com/aliaksandrkazlou/texts_comparison/blob/master/functions.py#L34), dashes and hyphens are grouped together. However

> 1. Во-первых
> 2. сделало из него француза — он переехал 

Look different enough. I suggest to analyze them separately. We still can include hyphens in the dashes group like this `" - "`

**Comment by mickolka** [comment]
It is a totally legitimate concern. It appears that now we only detect "dash" hyphens of the `" - "` kind that you've mentioned. Hyphens from your 1st example are part of the word tokens, so the logic will be a bit different to count those.

**Comment by mickolka** [comment]
One of the side effects is that I've noticed that hyphens were breaking up words previously 🤓  Now we should have corrected word counts for cases like `"бело-красно-белый"`, and in cases like `"фото- и видеоматериалы"` we should correctly identify a hyphen as well 🚀
